In [1]:
import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# import numpy as np

In [14]:
df1 = pd.read_csv("LOL_items_stats.csv", encoding='utf-8', delimiter=';')
df1

,Item,Cost,Sell,AD,AS,Crit,LS,APen,AP,AH,...,MP5,HSP,OVamp,MPen,Health,Armor,MR,HP5,MS,Maps
0,Abyssal Mask,2700,1890.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,400.0,NaN,60.0,NaN,NaN,All
1,Aegis of the Legion,1500,1050.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,30.0,30.0,NaN,NaN,All
2,Aether Wisp,850,595.0,NaN,NaN,NaN,NaN,NaN,30.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,All
3,Amplifying Tome,435,304.5,NaN,NaN,NaN,NaN,NaN,20.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,All
4,Archangel's Staff,3000,2100.0,NaN,NaN,NaN,NaN,NaN,65.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,All
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Zeal,1050,735.0,NaN,0.18,0.15,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,All
190,Zeke's Convergence,2400,1680.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,...,NaN,NaN,NaN,NaN,250.0,25.0,NaN,NaN,NaN,All
191,Zhonya's Hourglass,2600,1820.0,NaN,NaN,NaN,NaN,NaN,65.0,10.0,...,NaN,NaN,NaN,NaN,NaN,45.0,NaN,NaN,NaN,All
192,Anathema's Chains,2500,1750.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,...,NaN,NaN,NaN,NaN,650.0,NaN,NaN,NaN,NaN,All
193,Hullbreaker,2800,1960.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,300.0,NaN,NaN,1.25,NaN,NaN

In [23]:
file = "LOL_champions_stats.csv"
# df2 = df2 = pd.read_csv(file)
df2 = pd.read_csv(file,encoding='ISO-8859-1', delimiter=';')
df2.head()

,champion_name,champion_title,class,playstyle,date_release,last_change,blue_essence_price,rp_price,ressource,HP,...,AR,AR+,AR_lvl18,MR,MR+,MR_lvl18,MS,MS_lvl18,range,range_lvl18
0,Aatrox,the Darkin Blade,Fighter,Juggernaut,13/06/2013,V11.2,4800,880,Blood Well,580.0,...,38.0,3.25,93.25,32.0,1.25,53.25,345,345,175,175
1,Ahri,the Nine-Tailed Fox,Mage,Burst,14/12/2011,V11.1,3150,790,Mana,526.0,...,21.0,3.50,80.50,30.0,0.50,38.50,330,330,550,550
2,Akali,the Rogue Assassin,Slayer,Assassin,11/05/2010,V11.10,3150,790,Energy,500.0,...,23.0,3.50,82.50,37.0,1.25,58.25,345,345,125,125
3,Alistar,the Minotaur,Tank,Vanguard,21/02/2009,V11.8,1350,585,Mana,600.0,...,44.0,3.50,103.50,32.0,1.25,53.25,330,330,125,125
4,Amumu,the Sad Mummy,Tank,Vanguard,26/06/2009,V11.7,450,260,Mana,615.0,...,30.0,3.80,94.60,32.0,1.25,53.25,335,335,125,125

In [18]:
import chardet
with open(file, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))
result

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

In [ ]:
file = "/content/lol_champion_stats_en.csv"
# df3 = pd.read_csv(file)
df3 = pd.read_csv(file,encoding='ISO-8859-1', delimiter=';')
df3

In [ ]:
# file1 = "/content/LOL_items_stats.csv"
# file2 = "/content/lol_champion_stats_en.csv"
df1 = spark.read.csv(file1,encoding='ISO-8859-1', header=True, sep =';')
# df1 = pd.read_csv(file1,encoding='ISO-8859-1', delimiter=';')
# df2 = pd.read_csv(file2,encoding='ISO-8859-1', delimiter=';')
# df1.show()

In [15]:
df2 = pd.read_csv("LOL_champions_stats.csv", encoding='utf-8', delimiter=';')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 20650: invalid continuation byte

In [11]:
df3 = pd.read_csv("lol_champion_stats_en.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 21435: invalid continuation byte